# This tells Spring to load the .env file
spring.config.import=optional:file:../../.env

spring.application.name=Auth
server.port=8080

# ==========================================
# DATABASE CONFIGURATION
# ==========================================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/talentgrid}
spring.datasource.username=${DB_USERNAME:talentgrid}
spring.datasource.password=${DB_PASSWORD:talentgrid}

# ==========================================
# JPA CONFIGURATION
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# JWT CONFIGURATION
# ==========================================

jwt.secret=${JWT_SECRET:ForgeAINativeWorkforceIntelligencePlatform}
#jwt.expiration=900000
jwt.expiration=604800000
jwt.refresh-expiration=604800000
jwt.issuer=auth-service

# ==========================================
# GOOGLE OAUTH2
# ==========================================

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:542366028313-v92b5vssta79ptjsfli1u4kr4nci8njg.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET: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}

logging.level.org.springframework.security.oauth2=TRACE

spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# ==========================================
# LOGGING
# ==========================================

logging.level.org.springframework.security=DEBUG

spring.data.redis.host=localhost
spring.data.redis.port=6379

# ==========================================
# KAFKA CONFIGURATION
# ==========================================
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false