
# Make config server optional
spring.config.import=optional:configserver:http://localhost:8888

# Server configuration
server.port=8086
spring.application.name=workforce-service

spring.datasource.url=jdbc:postgresql://localhost:5432/talentgrid
spring.datasource.username=postgres
spring.datasource.password=abhi
spring.datasource.driver-class-name=org.postgresql.Driver