package com.talentgrid.shared.auth.constants;

/**
 * Centralized constants for JWT claim names and token metadata
 * used across all TalentGrid microservices.
 *
 * <p>Responsibilities:
 * <ul>
 *   <li>Define standard JWT claim keys</li>
 *   <li>Define token type identifiers</li>
 *   <li>Define audience identifiers</li>
 *   <li>Ensure consistency between token generation and validation</li>
 * </ul>
 *
 * <p>All JWT-related string literals must be defined here
 * to prevent drift between auth-service and consuming services.
 */
public final class JwtConstants {

    private JwtConstants() {
    }

    /** JWT custom claim key for the user's email address. */
    public static final String EMAIL = "email";

    /** JWT custom claim key for the user's assigned roles. */
    public static final String ROLES = "roles";

    /** JWT custom claim key for the user's granted scopes (permissions). */
    public static final String SCOPES = "scopes";

    /** JWT custom claim key for the token type discriminator. */
    public static final String TOKEN_TYPE = "token_type";

    /** JWT custom claim key for the authorization version counter. */
    public static final String AUTH_VERSION = "authVersion";

    /** Token type value for access tokens. */
    public static final String ACCESS_TOKEN = "access";

    /** Token type value for refresh tokens. */
    public static final String REFRESH_TOKEN = "refresh";

    /** Default audience value for API gateway routing. */
    public static final String API_GATEWAY = "api-gateway";

    /** Default issuer identifier for tokens generated by auth-service. */
    public static final String ISSUER = "auth-service";
}