# These credentials are automatically injected into application.properties
# This file is excluded from Git, so your credentials are safe!

MAIL_USERNAME=sirraveerapratap@gmail.com
MAIL_PASSWORD=zuvruqpmiyvomdgm
