spring.config.import=optional:file:../../.env[.properties]

spring.application.name=application-service
server.port=${APPLICATION_SERVICE_PORT:8086}

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/talentgrid}
spring.datasource.username=${DB_USERNAME:talentgrid}
spring.datasource.password=${DB_PASSWORD:talentgrid}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Must match JWT_SECRET in user-auth-service .env exactly
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
# Flyway
spring.flyway.baseline-on-migrate=true

# Spring Cloud
spring.cloud.compatibility-verifier.enabled=false

# Swagger
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

# MVC path matching
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Service URLs
candidate.service.url=${CANDIDATE_SERVICE_URL:http://${CANDIDATE_SERVICE_HOST:localhost}:${CANDIDATE_SERVICE_PORT:8085}}
demand.service.url=${DEMAND_SERVICE_URL:http://${DEMAND_SERVICE_HOST:localhost}:${DEMAND_SERVICE_PORT:8082}}

# OpenAI
#openai.api-key=${OPENAI_API_KEY:dummy_openai_api_key}

gemini.api-key=${GEMINI_API_KEY:}
gemini.model=${GEMINI_MODEL:gemini-2.5-flash}
gemini.base-url=${GEMINI_BASE_URL:https://generativelanguage.googleapis.com/v1beta}
# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=true

spring.kafka.consumer.group-id=application-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.talentgrid.*
spring.kafka.consumer.properties.spring.json.value.default.type=com.talentgrid.kafka.events.base.BaseEvent
talentgrid.kafka.auth-consumer.enabled=true
