server:
  port: 8085

spring:

  application:
    name: talentgrid-audit-service

  datasource:
    url: jdbc:postgresql://localhost:5432/talentgrid
    username: astephanas
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: audit-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: "*"
            value:
              default:
                type: com.talentgrid.kafka.events.base.BaseEvent

logging:
  level:
    root: INFO
    com.talentgrid.auditservice: DEBUG
    org.springframework.kafka: INFO