package com.talentgrid.demand.config;

import com.talentgrid.demand.domain.entity.JobTitle;
import com.talentgrid.demand.domain.entity.Skill;
import com.talentgrid.demand.repository.JobTitleRepository;
import com.talentgrid.demand.repository.SkillRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.DependsOn;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Slf4j
@Component
@DependsOn("entityManagerFactory") // ← ensures schema is applied before seeding
@RequiredArgsConstructor
public class SkillDataInitializer implements CommandLineRunner {

    private final SkillRepository skillRepository;
    private final JobTitleRepository jobTitleRepository;

    @Override
    @Transactional
    public void run(String... args) throws Exception {
        try {
            long skillCount = skillRepository.count();
            log.info("=================================================");
            log.info("SKILLS TABLE COUNT ACCORDING TO SPRING BOOT: {}", skillCount);
            log.info("=================================================");

            if (skillCount == 0) {
                log.info("No skills found. Seeding initial skills...");
                skillRepository.saveAll(List.of(
                        createSkill(1L, "Java"),
                        createSkill(2L, "Spring Boot"),
                        createSkill(3L, "Kafka"),
                        createSkill(4L, "PostgreSQL"),
                        createSkill(5L, "Microservices"),
                        createSkill(6L, "Docker"),
                        createSkill(7L, "Kubernetes"),
                        createSkill(8L, "AWS"),
                        createSkill(9L, "Azure"),
                        createSkill(10L, "REST API"),
                        createSkill(11L, "Hibernate"),
                        createSkill(12L, "JUnit"),
                        createSkill(13L, "React"),
                        createSkill(14L, "Angular"),
                        createSkill(15L, "Python"),
                        createSkill(16L, "JavaScript"),
                        createSkill(17L, "TypeScript"),
                        createSkill(18L, "C"),
                        createSkill(19L, "C++"),
                        createSkill(20L, "C#"),
                        createSkill(21L, "Go"),
                        createSkill(22L, "Rust"),
                        createSkill(23L, "Kotlin"),
                        createSkill(24L, "Scala"),
                        createSkill(25L, "Swift"),
                        createSkill(26L, "PHP"),
                        createSkill(27L, "Ruby"),
                        createSkill(28L, "Perl"),
                        createSkill(29L, "Node.js"),
                        createSkill(30L, "Express.js"),
                        createSkill(31L, "Django"),
                        createSkill(32L, "Flask"),
                        createSkill(33L, "FastAPI"),
                        createSkill(34L, ".NET"),
                        createSkill(35L, "ASP.NET Core"),
                        createSkill(36L, "Spring Security"),
                        createSkill(37L, "Spring Cloud"),
                        createSkill(38L, "Spring Data JPA"),
                        createSkill(39L, "Maven"),
                        createSkill(40L, "Gradle"),
                        createSkill(41L, "Git"),
                        createSkill(42L, "GitHub"),
                        createSkill(43L, "GitLab"),
                        createSkill(44L, "Bitbucket"),
                        createSkill(45L, "Jenkins"),
                        createSkill(46L, "GitHub Actions"),
                        createSkill(47L, "GitLab CI/CD"),
                        createSkill(48L, "Terraform"),
                        createSkill(49L, "Ansible"),
                        createSkill(50L, "Helm"),
                        createSkill(51L, "OpenShift"),
                        createSkill(52L, "Linux"),
                        createSkill(53L, "Unix"),
                        createSkill(54L, "Bash"),
                        createSkill(55L, "Shell Scripting"),
                        createSkill(56L, "PowerShell"),
                        createSkill(57L, "Nginx"),
                        createSkill(58L, "Apache HTTP Server"),
                        createSkill(59L, "Redis"),
                        createSkill(60L, "MongoDB"),
                        createSkill(61L, "MySQL"),
                        createSkill(62L, "Oracle Database"),
                        createSkill(63L, "Microsoft SQL Server"),
                        createSkill(64L, "SQLite"),
                        createSkill(65L, "Cassandra"),
                        createSkill(66L, "Couchbase"),
                        createSkill(67L, "DynamoDB"),
                        createSkill(68L, "Elasticsearch"),
                        createSkill(69L, "OpenSearch"),
                        createSkill(70L, "RabbitMQ"),
                        createSkill(71L, "ActiveMQ"),
                        createSkill(72L, "Apache Camel"),
                        createSkill(73L, "Apache Spark"),
                        createSkill(74L, "Hadoop"),
                        createSkill(75L, "Apache Flink"),
                        createSkill(76L, "Apache Airflow"),
                        createSkill(77L, "Apache NiFi"),
                        createSkill(78L, "GraphQL"),
                        createSkill(79L, "gRPC"),
                        createSkill(80L, "SOAP"),
                        createSkill(81L, "OAuth 2.0"),
                        createSkill(82L, "OpenID Connect"),
                        createSkill(83L, "JWT"),
                        createSkill(84L, "WebSockets"),
                        createSkill(85L, "HTML5"),
                        createSkill(86L, "CSS3"),
                        createSkill(87L, "Bootstrap"),
                        createSkill(88L, "Tailwind CSS"),
                        createSkill(89L, "Material UI"),
                        createSkill(90L, "Redux"),
                        createSkill(91L, "Next.js"),
                        createSkill(92L, "Vue.js"),
                        createSkill(93L, "Nuxt.js"),
                        createSkill(94L, "Svelte"),
                        createSkill(95L, "Flutter"),
                        createSkill(96L, "React Native"),
                        createSkill(97L, "Android"),
                        createSkill(98L, "iOS"),
                        createSkill(99L, "Machine Learning"),
                        createSkill(100L, "Deep Learning"),
                        createSkill(101L, "TensorFlow"),
                        createSkill(102L, "PyTorch"),
                        createSkill(103L, "Scikit-learn"),
                        createSkill(104L, "Pandas"),
                        createSkill(105L, "NumPy"),
                        createSkill(106L, "OpenCV"),
                        createSkill(107L, "Data Science"),
                        createSkill(108L, "Artificial Intelligence"),
                        createSkill(109L, "Generative AI"),
                        createSkill(110L, "Large Language Models"),
                        createSkill(111L, "Prompt Engineering"),
                        createSkill(112L, "LangChain"),
                        createSkill(113L, "Vector Databases"),
                        createSkill(114L, "Pinecone"),
                        createSkill(115L, "Milvus"),
                        createSkill(116L, "ChromaDB"),
                        createSkill(117L, "FAISS"),
                        createSkill(118L, "CI/CD"),
                        createSkill(119L, "Data Analytics"),
                        createSkill(120L, "Business Intelligence"),
                        createSkill(121L, "Data Engineering"),
                        createSkill(122L, "Big Data"),
                        createSkill(123L, "Data Warehousing"),
                        createSkill(124L, "ETL"),
                        createSkill(125L, "ELT"),
                        createSkill(126L, "Data Mining"),
                        createSkill(127L, "Feature Engineering"),
                        createSkill(128L, "Data Visualization"),
                        createSkill(129L, "Power BI"),
                        createSkill(130L, "Tableau"),
                        createSkill(131L, "Apache Hive"),
                        createSkill(132L, "Apache Pig"),
                        createSkill(133L, "Databricks"),
                        createSkill(134L, "Snowflake"),
                        createSkill(135L, "Amazon Redshift"),
                        createSkill(136L, "Google BigQuery"),
                        createSkill(137L, "Azure Synapse Analytics"),
                        createSkill(138L, "MLOps"),
                        createSkill(139L, "MLflow"),
                        createSkill(140L, "Kubeflow"),
                        createSkill(141L, "Model Deployment"),
                        createSkill(142L, "Natural Language Processing"),
                        createSkill(143L, "Computer Vision"),
                        createSkill(144L, "Recommendation Systems"),
                        createSkill(145L, "Time Series Forecasting"),
                        createSkill(146L, "Reinforcement Learning"),
                        createSkill(147L, "Statistics"),
                        createSkill(148L, "Probability"),
                        createSkill(149L, "Linear Algebra"),
                        createSkill(150L, "Calculus"),
                        createSkill(151L, "A/B Testing"),
                        createSkill(152L, "Predictive Analytics"),
                        createSkill(153L, "Prescriptive Analytics"),
                        createSkill(154L, "R Programming"),
                        createSkill(155L, "MATLAB"),
                        createSkill(156L, "SAS"),
                        createSkill(157L, "SPSS"),
                        createSkill(158L, "Neo4j"),
                        createSkill(159L, "Graph Databases"),
                        createSkill(160L, "Apache Solr"),
                        createSkill(161L, "Prometheus"),
                        createSkill(162L, "Grafana"),
                        createSkill(163L, "Splunk"),
                        createSkill(164L, "SonarQube"),
                        createSkill(165L, "JUnit 5"),
                        createSkill(166L, "Mockito"),
                        createSkill(167L, "TestNG"),
                        createSkill(168L, "Cypress"),
                        createSkill(169L, "Selenium"),
                        createSkill(170L, "System Design"),
                        createSkill(171L, "Distributed Systems"),
                        createSkill(172L, "Design Patterns"),
                        createSkill(173L, "Object-Oriented Design"),
                        createSkill(174L, "Domain-Driven Design"),
                        createSkill(175L, "Event-Driven Architecture"),
                        createSkill(176L, "CQRS"),
                        createSkill(177L, "Event Sourcing"),
                        createSkill(178L, "Hexagonal Architecture"),
                        createSkill(179L, "Clean Architecture"),
                        createSkill(180L, "SOLID Principles"),
                        createSkill(181L, "Multithreading"),
                        createSkill(182L, "Concurrency"),
                        createSkill(183L, "Asynchronous Programming"),
                        createSkill(184L, "Reactive Programming"),
                        createSkill(185L, "Project Reactor"),
                        createSkill(186L, "RxJava"),
                        createSkill(187L, "Caching"),
                        createSkill(188L, "Database Optimization"),
                        createSkill(189L, "Query Optimization"),
                        createSkill(190L, "Connection Pooling"),
                        createSkill(191L, "Database Indexing"),
                        createSkill(192L, "Database Migration"),
                        createSkill(193L, "Liquibase"),
                        createSkill(194L, "Flyway"),
                        createSkill(195L, "API Gateway"),
                        createSkill(196L, "Service Discovery"),
                        createSkill(197L, "Load Balancing"),
                        createSkill(198L, "Circuit Breaker"),
                        createSkill(199L, "Resilience4j"),
                        createSkill(200L, "Feign Client"),
                        createSkill(201L, "API Versioning"),
                        createSkill(202L, "Rate Limiting"),
                        createSkill(203L, "Message Queues"),
                        createSkill(204L, "Apache Avro"),
                        createSkill(205L, "Protocol Buffers"),
                        createSkill(206L, "JSON"),
                        createSkill(207L, "XML"),
                        createSkill(208L, "YAML"),
                        createSkill(209L, "Authentication"),
                        createSkill(210L, "Authorization"),
                        createSkill(211L, "Role-Based Access Control"),
                        createSkill(212L, "Encryption"),
                        createSkill(213L, "SSL/TLS"),
                        createSkill(214L, "OWASP Top 10"),
                        createSkill(215L, "Application Security"),
                        createSkill(216L, "Secrets Management"),
                        createSkill(217L, "HashiCorp Vault"),
                        createSkill(218L, "Observability"),
                        createSkill(219L, "Distributed Tracing"),
                        createSkill(220L, "OpenTelemetry"),
                        createSkill(221L, "Log Aggregation"),
                        createSkill(222L, "Application Monitoring"),
                        createSkill(223L, "Performance Tuning"),
                        createSkill(224L, "Capacity Planning"),
                        createSkill(225L, "Chaos Engineering"),
                        createSkill(226L, "Blue-Green Deployment"),
                        createSkill(227L, "Canary Deployment"),
                        createSkill(228L, "Infrastructure as Code"),
                        createSkill(229L, "Virtualization"),
                        createSkill(230L, "Container Security"),
                        createSkill(231L, "Cloud Security"),
                        createSkill(232L, "Identity and Access Management"),
                        createSkill(233L, "Serverless Computing"),
                        createSkill(234L, "Edge Computing"),
                        createSkill(235L, "Virtual Private Cloud"),
                        createSkill(236L, "Networking"),
                        createSkill(237L, "TCP/IP"),
                        createSkill(238L, "DNS"),
                        createSkill(239L, "HTTP"),
                        createSkill(240L, "HTTPS"),
                        createSkill(241L, "Web Performance"),
                        createSkill(242L, "Accessibility"),
                        createSkill(243L, "Responsive Design"),
                        createSkill(244L, "Cross Browser Testing"),
                        createSkill(245L, "State Management"),
                        createSkill(246L, "Component Design"),
                        createSkill(247L, "UI Testing"),
                        createSkill(248L, "End-to-End Testing"),
                        createSkill(249L, "Contract Testing"),
                        createSkill(250L, "Integration Testing"),
                        createSkill(251L, "Unit Testing Best Practices"),
                        createSkill(252L, "Test Automation"),
                        createSkill(253L, "Performance Testing"),
                        createSkill(254L, "Load Testing"),
                        createSkill(255L, "Stress Testing"),
                        createSkill(256L, "Security Testing"),
                        createSkill(257L, "Static Code Analysis"),
                        createSkill(258L, "Code Review"),
                        createSkill(259L, "Technical Documentation"),
                        createSkill(260L, "Agile"),
                        createSkill(261L, "Scrum"),
                        createSkill(262L, "Kanban"),
                        createSkill(263L, "Jira"),
                        createSkill(264L, "Confluence"),
                        createSkill(265L, "Software Estimation"),
                        createSkill(266L, "Release Management"),
                        createSkill(267L, "Incident Management"),
                        createSkill(268L, "Root Cause Analysis"),
                        createSkill(269L, "Production Support"),
                        createSkill(270L, "Mentoring"),
                        createSkill(271L, "Technical Leadership"),
                        createSkill(272L, "Solution Architecture"),
                        createSkill(273L, "Enterprise Architecture"),
                        createSkill(274L, "Requirements Analysis"),
                        createSkill(275L, "Business Analysis"),
                        createSkill(276L, "Technical Writing"),
                        createSkill(277L, "Code Refactoring"),
                        createSkill(278L, "Legacy System Modernization"),
                        createSkill(279L, "Scalability"),
                        createSkill(280L, "High Availability"),
                        createSkill(281L, "Fault Tolerance"),
                        createSkill(282L, "Disaster Recovery"),
                        createSkill(283L, "Backup and Restore"),
                        createSkill(284L, "Configuration Management"),
                        createSkill(285L, "Release Automation"),
                        createSkill(286L, "Dependency Management"),
                        createSkill(287L, "Software Lifecycle"),
                        createSkill(288L, "Peer Programming"),
                        createSkill(289L, "Technical Interviewing"),
                        createSkill(290L, "Architecture Review"),
                        createSkill(291L, "Unix Shell"),
                        createSkill(292L, "Linux Administration"),
                        createSkill(293L, "Windows Server"),
                        createSkill(294L, "Active Directory"),
                        createSkill(295L, "LDAP"),
                        createSkill(296L, "Kerberos"),
                        createSkill(297L, "Single Sign-On"),
                        createSkill(298L, "SAML"),
                        createSkill(299L, "IAM"),
                        createSkill(300L, "Zero Trust Security"),

                        createSkill(301L, "Network Security"),
                        createSkill(302L, "Firewall Configuration"),
                        createSkill(303L, "VPN"),
                        createSkill(304L, "Reverse Proxy"),
                        createSkill(305L, "Web Application Firewall"),
                        createSkill(306L, "API Security"),
                        createSkill(307L, "Secure Coding"),
                        createSkill(308L, "Threat Modeling"),
                        createSkill(309L, "Vulnerability Assessment"),
                        createSkill(310L, "Penetration Testing"),

                        createSkill(311L, "Secure SDLC"),
                        createSkill(312L, "Dependency Scanning"),
                        createSkill(313L, "Container Orchestration"),
                        createSkill(314L, "Cloud Migration"),
                        createSkill(315L, "Hybrid Cloud"),
                        createSkill(316L, "Multi Cloud"),
                        createSkill(317L, "Cloud Cost Optimization"),
                        createSkill(318L, "Cloud Governance"),
                        createSkill(319L, "Cloud Monitoring"),
                        createSkill(320L, "Cloud Automation"),

                        createSkill(321L, "Data Modeling"),
                        createSkill(322L, "Database Design"),
                        createSkill(323L, "Normalization"),
                        createSkill(324L, "Denormalization"),
                        createSkill(325L, "Stored Procedures"),
                        createSkill(326L, "Database Replication"),
                        createSkill(327L, "Partitioning"),
                        createSkill(328L, "Sharding"),
                        createSkill(329L, "Data Integrity"),
                        createSkill(330L, "Transaction Management"),

                        createSkill(331L, "Event Streaming"),
                        createSkill(332L, "Streaming Analytics"),
                        createSkill(333L, "Batch Processing"),
                        createSkill(334L, "Workflow Automation"),
                        createSkill(335L, "Metadata Management"),
                        createSkill(336L, "Master Data Management"),
                        createSkill(337L, "Data Governance"),
                        createSkill(338L, "Data Quality"),
                        createSkill(339L, "Data Lineage"),
                        createSkill(340L, "Data Catalog"),

                        createSkill(341L, "Feature Stores"),
                        createSkill(342L, "Model Monitoring"),
                        createSkill(343L, "Model Drift Detection"),
                        createSkill(344L, "Responsible AI"),
                        createSkill(345L, "Explainable AI"),
                        createSkill(346L, "AI Ethics"),
                        createSkill(347L, "AI Governance"),
                        createSkill(348L, "LLMOps"),
                        createSkill(349L, "Retrieval Augmented Generation"),
                        createSkill(350L, "Embedding Models"),

                        createSkill(351L, "Semantic Search"),
                        createSkill(352L, "Knowledge Graphs"),
                        createSkill(353L, "Agentic AI"),
                        createSkill(354L, "AI Agents"),
                        createSkill(355L, "Function Calling"),
                        createSkill(356L, "Prompt Chaining"),
                        createSkill(357L, "Context Engineering"),
                        createSkill(358L, "Fine Tuning"),
                        createSkill(359L, "Model Evaluation"),
                        createSkill(360L, "Inference Optimization"),

                        createSkill(361L, "Clean Code"),
                        createSkill(362L, "Code Quality"),
                        createSkill(363L, "Static Analysis"),
                        createSkill(364L, "Dynamic Analysis"),
                        createSkill(365L, "Secure Architecture"),
                        createSkill(366L, "Enterprise Integration"),
                        createSkill(367L, "Message Routing"),
                        createSkill(368L, "Workflow Design"),
                        createSkill(369L, "Business Process Automation"),
                        createSkill(370L, "Digital Transformation"),

                        createSkill(371L, "Mobile Backend"),
                        createSkill(372L, "Progressive Web Apps"),
                        createSkill(373L, "Offline Synchronization"),
                        createSkill(374L, "Push Notifications"),
                        createSkill(375L, "Real-Time Systems"),
                        createSkill(376L, "Streaming APIs"),
                        createSkill(377L, "Graph Processing"),
                        createSkill(378L, "Distributed Caching"),
                        createSkill(379L, "Memory Optimization"),
                        createSkill(380L, "CPU Optimization"),

                        createSkill(381L, "Thread Synchronization"),
                        createSkill(382L, "Garbage Collection"),
                        createSkill(383L, "Heap Analysis"),
                        createSkill(384L, "JVM Performance"),
                        createSkill(385L, "Profiling"),
                        createSkill(386L, "Benchmarking"),
                        createSkill(387L, "Latency Optimization"),
                        createSkill(388L, "Horizontal Scaling"),
                        createSkill(389L, "Vertical Scaling"),
                        createSkill(390L, "Performance Engineering"),

                        createSkill(391L, "Business Continuity"),
                        createSkill(392L, "Risk Assessment"),
                        createSkill(393L, "Compliance"),
                        createSkill(394L, "GDPR"),
                        createSkill(395L, "ISO 27001"),
                        createSkill(396L, "SOC 2"),
                        createSkill(397L, "PCI DSS"),
                        createSkill(398L, "HIPAA"),
                        createSkill(399L, "Audit Readiness"),
                        createSkill(400L, "Policy Management"),

                        createSkill(401L, "Problem Solving"),
                        createSkill(402L, "Critical Thinking"),
                        createSkill(403L, "Analytical Thinking"),
                        createSkill(404L, "Decision Making"),
                        createSkill(405L, "Creative Thinking"),
                        createSkill(406L, "Innovation"),
                        createSkill(407L, "Strategic Thinking"),
                        createSkill(408L, "Systems Thinking"),
                        createSkill(409L, "Learning Agility"),
                        createSkill(410L, "Adaptability"),

                        createSkill(411L, "Communication"),
                        createSkill(412L, "Presentation Skills"),
                        createSkill(413L, "Public Speaking"),
                        createSkill(414L, "Technical Communication"),
                        createSkill(415L, "Active Listening"),
                        createSkill(416L, "Negotiation"),
                        createSkill(417L, "Conflict Resolution"),
                        createSkill(418L, "Collaboration"),
                        createSkill(419L, "Teamwork"),
                        createSkill(420L, "Cross Functional Collaboration"),

                        createSkill(421L, "Leadership"),
                        createSkill(422L, "People Management"),
                        createSkill(423L, "Coaching"),
                        createSkill(424L, "Mentorship"),
                        createSkill(425L, "Delegation"),
                        createSkill(426L, "Performance Management"),
                        createSkill(427L, "Talent Development"),
                        createSkill(428L, "Stakeholder Management"),
                        createSkill(429L, "Executive Communication"),
                        createSkill(430L, "Vision Setting"),

                        createSkill(431L, "Customer Focus"),
                        createSkill(432L, "User Empathy"),
                        createSkill(433L, "Product Thinking"),
                        createSkill(434L, "Business Acumen"),
                        createSkill(435L, "Ownership"),
                        createSkill(436L, "Accountability"),
                        createSkill(437L, "Time Management"),
                        createSkill(438L, "Prioritization"),
                        createSkill(439L, "Planning"),
                        createSkill(440L, "Execution"),

                        createSkill(441L, "Attention to Detail"),
                        createSkill(442L, "Quality Mindset"),
                        createSkill(443L, "Continuous Improvement"),
                        createSkill(444L, "Process Improvement"),
                        createSkill(445L, "Knowledge Sharing"),
                        createSkill(446L, "Documentation"),
                        createSkill(447L, "Facilitation"),
                        createSkill(448L, "Workshop Facilitation"),
                        createSkill(449L, "Brainstorming"),
                        createSkill(450L, "Research"),

                        createSkill(451L, "Emotional Intelligence"),
                        createSkill(452L, "Empathy"),
                        createSkill(453L, "Resilience"),
                        createSkill(454L, "Stress Management"),
                        createSkill(455L, "Self Motivation"),
                        createSkill(456L, "Growth Mindset"),
                        createSkill(457L, "Professional Ethics"),
                        createSkill(458L, "Integrity"),
                        createSkill(459L, "Reliability"),
                        createSkill(460L, "Work Ethic"),

                        createSkill(461L, "Change Management"),
                        createSkill(462L, "Organizational Skills"),
                        createSkill(463L, "Resource Management"),
                        createSkill(464L, "Vendor Management"),
                        createSkill(465L, "Client Management"),
                        createSkill(466L, "Service Delivery"),
                        createSkill(467L, "Consulting"),
                        createSkill(468L, "Requirement Gathering"),
                        createSkill(469L, "Solution Design"),
                        createSkill(470L, "Architecture Governance"),

                        createSkill(471L, "Release Planning"),
                        createSkill(472L, "Sprint Planning"),
                        createSkill(473L, "Backlog Grooming"),
                        createSkill(474L, "User Story Writing"),
                        createSkill(475L, "Acceptance Criteria"),
                        createSkill(476L, "Sprint Retrospective"),
                        createSkill(477L, "Daily Standup"),
                        createSkill(478L, "Agile Coaching"),
                        createSkill(479L, "Scaled Agile"),
                        createSkill(480L, "Lean Software Development"),

                        createSkill(481L, "Value Stream Mapping"),
                        createSkill(482L, "Design Thinking"),
                        createSkill(483L, "Customer Journey Mapping"),
                        createSkill(484L, "Wireframing"),
                        createSkill(485L, "Prototyping"),
                        createSkill(486L, "Usability Testing"),
                        createSkill(487L, "Accessibility Testing"),
                        createSkill(488L, "Localization"),
                        createSkill(489L, "Internationalization"),
                        createSkill(490L, "Technical Roadmapping"),

                        // ── Cybersecurity Engineer (beginner → master) ────────────────────
                        createSkill(491L, "Network Fundamentals"),
                        createSkill(492L, "Wireshark"),
                        createSkill(493L, "Nmap"),
                        createSkill(494L, "Burp Suite"),
                        createSkill(495L, "Metasploit"),
                        createSkill(496L, "SIEM"),
                        createSkill(497L, "IDS / IPS"),
                        createSkill(498L, "SOC Operations"),
                        createSkill(499L, "Incident Response"),
                        createSkill(500L, "Digital Forensics"),
                        createSkill(501L, "CVE Analysis"),
                        createSkill(502L, "Security Hardening"),
                        createSkill(503L, "Red Teaming"),
                        createSkill(504L, "Blue Teaming"),
                        createSkill(505L, "Malware Analysis"),

                        // ── Platform Engineer (beginner → master) ─────────────────────────
                        createSkill(506L, "ArgoCD"),
                        createSkill(507L, "FluxCD"),
                        createSkill(508L, "Crossplane"),
                        createSkill(509L, "Backstage"),
                        createSkill(510L, "Istio"),
                        createSkill(511L, "Linkerd"),
                        createSkill(512L, "Service Mesh"),
                        createSkill(513L, "OPA / Gatekeeper"),
                        createSkill(514L, "Kyverno"),
                        createSkill(515L, "Developer Platform"),
                        createSkill(516L, "Golden Path"),
                        createSkill(517L, "Internal Developer Portal"),

                        // ── Site Reliability Engineer (beginner → master) ─────────────────
                        createSkill(518L, "SLI / SLO / SLA"),
                        createSkill(519L, "Error Budget"),
                        createSkill(520L, "On-Call Management"),
                        createSkill(521L, "PagerDuty"),
                        createSkill(522L, "Runbook Automation"),
                        createSkill(523L, "Postmortem Analysis"),
                        createSkill(524L, "Toil Reduction"),
                        createSkill(525L, "Reliability Engineering"),
                        createSkill(526L, "Blameless Culture"),
                        createSkill(527L, "Error Tracking"),
                        createSkill(528L, "Mean Time to Recovery"),

                        // ── Technical Project Manager (beginner → master) ─────────────────
                        createSkill(529L, "Project Charter"),
                        createSkill(530L, "Gantt Chart"),
                        createSkill(531L, "Critical Path Method"),
                        createSkill(532L, "Risk Management"),
                        createSkill(533L, "Budget Management"),
                        createSkill(534L, "RAID Log"),
                        createSkill(535L, "Earned Value Management"),
                        createSkill(536L, "Program Management"),
                        createSkill(537L, "OKR Tracking"),
                        createSkill(538L, "Change Control"),
                        createSkill(539L, "MS Project"),
                        createSkill(540L, "Delivery Management"),

                        // ── Data Scientist (additions — beginner → master) ────────────────
                        createSkill(541L, "Jupyter Notebooks"),
                        createSkill(542L, "Hugging Face"),
                        createSkill(543L, "AutoML"),
                        createSkill(544L, "Hypothesis Testing"),
                        createSkill(545L, "Bayesian Analysis"),
                        createSkill(546L, "Statistical Modeling"),
                        createSkill(547L, "Survival Analysis"),
                        createSkill(548L, "Causal Inference"),
                        createSkill(549L, "Model Interpretability"),
                        createSkill(550L, "Experiment Design"),

                        // ── Cloud-specific services ───────────────────────────────────────
                        createSkill(551L, "AWS Lambda"),
                        createSkill(552L, "AWS EKS"),
                        createSkill(553L, "AWS S3"),
                        createSkill(554L, "AWS RDS"),
                        createSkill(555L, "Amazon SQS / SNS"),
                        createSkill(556L, "AWS CloudFormation"),
                        createSkill(557L, "Google Cloud Platform"),
                        createSkill(558L, "Google Kubernetes Engine"),
                        createSkill(559L, "Azure Kubernetes Service"),
                        createSkill(560L, "Azure Functions"),

                        // ── Modern frontend & build tooling ───────────────────────────────
                        createSkill(561L, "Webpack"),
                        createSkill(562L, "Vite"),
                        createSkill(563L, "ESLint / Prettier"),
                        createSkill(564L, "Storybook"),
                        createSkill(565L, "Jest"),
                        createSkill(566L, "Vitest"),
                        createSkill(567L, "D3.js"),
                        createSkill(568L, "Three.js"),
                        createSkill(569L, "WebAssembly"),
                        createSkill(570L, "WebGL"),

                        // ── Advanced testing tools ────────────────────────────────────────
                        createSkill(571L, "Playwright"),
                        createSkill(572L, "k6"),
                        createSkill(573L, "Gatling"),
                        createSkill(574L, "JMeter"),
                        createSkill(575L, "Locust"),
                        createSkill(576L, "Artillery"),
                        createSkill(577L, "WireMock"),
                        createSkill(578L, "Pact"),
                        createSkill(579L, "Mutation Testing"),
                        createSkill(580L, "Test Coverage Analysis"),

                        // ── Data lakehouse & pipeline tools ───────────────────────────────
                        createSkill(581L, "dbt"),
                        createSkill(582L, "Great Expectations"),
                        createSkill(583L, "Delta Lake"),
                        createSkill(584L, "Apache Iceberg"),
                        createSkill(585L, "Apache Hudi"),
                        createSkill(586L, "Prefect"),
                        createSkill(587L, "Dagster"),
                        createSkill(588L, "ClickHouse"),
                        createSkill(589L, "Apache Druid"),
                        createSkill(590L, "Apache Pinot"),

                        // ── Observability platforms ───────────────────────────────────────
                        createSkill(591L, "Datadog"),
                        createSkill(592L, "New Relic"),
                        createSkill(593L, "Dynatrace"),
                        createSkill(594L, "AppDynamics"),
                        createSkill(595L, "Jaeger"),
                        createSkill(596L, "Zipkin"),
                        createSkill(597L, "Sentry"),
                        createSkill(598L, "Elastic APM"),
                        createSkill(599L, "Fluentd"),
                        createSkill(600L, "Fluent Bit"),

                        // ── Additional programming languages ──────────────────────────────
                        createSkill(601L, "Julia"),
                        createSkill(602L, "Elixir"),
                        createSkill(603L, "Dart"),
                        createSkill(604L, "Zig"),
                        createSkill(605L, "Erlang"),
                        createSkill(606L, "Haskell"),
                        createSkill(607L, "F#"),
                        createSkill(608L, "Clojure"),
                        createSkill(609L, "Groovy"),
                        createSkill(610L, "Lua"),

                        // ── API design & tooling ──────────────────────────────────────────
                        createSkill(611L, "Postman"),
                        createSkill(612L, "OpenAPI / Swagger"),
                        createSkill(613L, "Kong API Gateway"),
                        createSkill(614L, "Traefik"),
                        createSkill(615L, "Apigee"),
                        createSkill(616L, "AsyncAPI"),
                        createSkill(617L, "REST Assured"),
                        createSkill(618L, "Insomnia"),
                        createSkill(619L, "API Mocking"),
                        createSkill(620L, "API Documentation"),

                        // ── GitOps, DevSecOps & supply chain ─────────────────────────────
                        createSkill(621L, "GitOps"),
                        createSkill(622L, "Policy as Code"),
                        createSkill(623L, "FinOps"),
                        createSkill(624L, "DevSecOps"),
                        createSkill(625L, "Supply Chain Security"),
                        createSkill(626L, "SBOM"),
                        createSkill(627L, "Container Registry"),
                        createSkill(628L, "Image Scanning"),
                        createSkill(629L, "Signed Container Images"),
                        createSkill(630L, "Secrets Rotation"),

                        // ── AI platform SDKs & LLMOps tooling ────────────────────────────
                        createSkill(631L, "Amazon SageMaker"),
                        createSkill(632L, "Google Vertex AI"),
                        createSkill(633L, "Azure Machine Learning"),
                        createSkill(634L, "OpenAI API"),
                        createSkill(635L, "Anthropic Claude API"),
                        createSkill(636L, "Gemini API"),
                        createSkill(637L, "Cohere API"),
                        createSkill(638L, "RLHF"),
                        createSkill(639L, "Model Quantization"),
                        createSkill(640L, "Model Distillation"),

                        // ── Collaboration & productivity tooling ──────────────────────────
                        createSkill(641L, "Notion"),
                        createSkill(642L, "Linear"),
                        createSkill(643L, "Miro"),
                        createSkill(644L, "Figma"),
                        createSkill(645L, "Lucidchart"),
                        createSkill(646L, "Slack Workflows"),
                        createSkill(647L, "Microsoft Teams"),
                        createSkill(648L, "Asana"),
                        createSkill(649L, "Monday.com"),
                        createSkill(650L, "Trello")));
                log.info("Initial skills seeded.");
            }

            if (jobTitleRepository.count() == 0) {
                log.info("No job titles found. Seeding initial job titles...");
                jobTitleRepository.saveAll(List.of(
                        createJobTitle(1L, "Software Engineer"),
                        createJobTitle(2L, "Senior Software Engineer"),
                        createJobTitle(3L, "Lead Software Engineer"),
                        createJobTitle(4L, "Staff Engineer"),
                        createJobTitle(5L, "Principal Engineer"),
                        createJobTitle(6L, "Engineering Manager"),
                        createJobTitle(7L, "Technical Architect"),
                        createJobTitle(8L, "Backend Engineer"),
                        createJobTitle(9L, "Frontend Engineer"),
                        createJobTitle(10L, "Full Stack Engineer"),
                        createJobTitle(11L, "DevOps Engineer"),
                        createJobTitle(12L, "Cloud Engineer"),
                        createJobTitle(13L, "Data Engineer"),
                        createJobTitle(14L, "QA Engineer"),
                        createJobTitle(15L, "SDET"),
                        createJobTitle(16L, "Data Scientist"),
                        createJobTitle(17L, "Cybersecurity Engineer"),
                        createJobTitle(18L, "Platform Engineer"),
                        createJobTitle(19L, "Technical Project Manager"),
                        createJobTitle(20L, "Site Reliability Engineer")));
                log.info("Initial job titles seeded.");
            }
        } catch (Exception ex) {
            log.error("=================================================");
            log.error("SkillDataInitializer FAILED — the 'skills' or 'job_titles' table may not exist yet.");
            log.error("Fix: ensure the pgvector extension is installed and the schema has been created.");
            log.error("Run on your PostgreSQL DB:  CREATE EXTENSION IF NOT EXISTS vector;");
            log.error("Then restart the service. Underlying error: {}", ex.getMessage());
            log.error("=================================================");
            throw ex; // re-throw so the boot failure is still explicit
        }
    }

    private Skill createSkill(Long id, String name) {
        Skill skill = new Skill();
        // skill.setSkillId(id); // ID is auto-generated by IDENTITY
        skill.setSkillName(name);
        return skill;
    }

    private JobTitle createJobTitle(Long id, String name) {
        JobTitle jobTitle = new JobTitle();
        // jobTitle.setJobTitleId(id); // ID is auto-generated by IDENTITY
        jobTitle.setTitleName(name);
        return jobTitle;
    }
}